FROM nginx:alpine

ARG API_URL
ENV API_URL=https://travel-planner-backend-xzzp.onrender.com

COPY . /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN chmod -R 755 /usr/share/nginx/html/

# Inject backend API URL
RUN sed -i "s|http://localhost:8000|${API_URL}|g" /usr/share/nginx/html/script.js

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


# FROM nginx:alpine

# # Copy static files to nginx html directory
# COPY . /usr/share/nginx/html/

# # Copy custom nginx config
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# # Fix potential file permissions
# RUN chmod -R 755 /usr/share/nginx/html/

# # Update API URL for production
# RUN sed -i 's|http://localhost:8000|/api|g' /usr/share/nginx/html/script.js

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]